import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = (os.getenv("BOT_TOKEN") or "").strip()
CHAT_ID_RAW = (os.getenv("CHAT_ID") or "").strip()

if not BOT_TOKEN:
    raise ValueError("BOT_TOKEN не задан")

CHAT_ID = int(CHAT_ID_RAW) if CHAT_ID_RAW else None

SCAN_INTERVAL = 300
AUTO_ALERTS = True

STRONG_DIP_PERCENT = -30
STRONG_PUMP_PERCENT = 30
MIN_ABSOLUTE_MOVE = 0.02
CHEAP_MARKET_MAX_PRICE = 0.01
CHEAP_MARKET_MIN_MOVE = 0.002
MIN_ALERT_LIQUIDITY_POLITICS = 500_000
MIN_ALERT_LIQUIDITY_CRYPTO = 10_000
MIN_ALERT_LIQUIDITY_SPORTS = 10_000
MIN_ALERT_LIQUIDITY_ENTERTAINMENT = 10_000
MIN_ALERT_LIQUIDITY_DEFAULT = 10_000

AUTO_VALUE_ALERTS = False
ALERT_COOLDOWN_HOURS = 24

# AI Engine работает в теневом режиме и не блокирует уведомления.
AI_MIN_TRAINING_SAMPLES = 200
AI_SUCCESS_MOVE_PERCENT = 20.0
AI_SHOW_IN_ALERTS = True

# Opportunity Engine: отдельные уведомления о качественных рынках,
# даже если новое движение цены уже завершилось.
AUTO_OPPORTUNITY_ALERTS = True
OPPORTUNITY_MIN_SCORE = 90
OPPORTUNITY_MIN_AI_QUALITY = 70
OPPORTUNITY_MAX_AI_RISK = 45
OPPORTUNITY_MIN_LIQUIDITY = 100_000
OPPORTUNITY_MAX_PRICE = 0.05
OPPORTUNITY_COOLDOWN_HOURS = 72
OPPORTUNITY_MAX_ALERTS_PER_SCAN = 3

SNAPSHOT_HIGH_SCORE = 70
SNAPSHOT_MEDIUM_SCORE = 40

SNAPSHOT_HIGH_INTERVAL_MINUTES = 5
SNAPSHOT_MEDIUM_INTERVAL_MINUTES = 30
SNAPSHOT_LOW_INTERVAL_MINUTES = 120

SNAPSHOT_FORCE_PRICE_CHANGE_PERCENT = 2.0
SNAPSHOT_FORCE_LIQUIDITY_CHANGE_PERCENT = 5.0
SNAPSHOT_FORCE_SCORE_CHANGE = 4
SNAPSHOT_FORCE_MARKET_MOVE_PERCENT = 20.0

MARKET_SNAPSHOTS_RETENTION_DAYS = 7
PRICES_RETENTION_DAYS = 30

DATABASE_CLEANUP_INTERVAL_HOURS = 24
DATABASE_VACUUM_INTERVAL_DAYS = 7

# VACUUM запускается, если не менее 15% базы занимает
# пространство от уже удалённых записей.
DATABASE_VACUUM_MIN_FREE_RATIO = 0.15