import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = (os.getenv("BOT_TOKEN") or "").strip()
CHAT_ID_RAW = (os.getenv("CHAT_ID") or "").strip()

if not BOT_TOKEN:
    raise ValueError("BOT_TOKEN не задан")

CHAT_ID = int(CHAT_ID_RAW) if CHAT_ID_RAW else None

SCAN_INTERVAL = 300
AUTO_ALERTS = True

# Quality Live Mode v1 — меньше алертов, приоритет Strong continuation.
# ВАЖНО: AI Memory продолжает записывать все обнаруженные сигналы до live-фильтра.
# Quality Engine v3: live high-precision delivery gate.
QUALITY_ENGINE_V3_MODE = True

QUALITY_LIVE_MODE = True
QUALITY_LIVE_SCORE_MIN = 60
QUALITY_LIVE_SCORE_MAX = 74
QUALITY_LIVE_BLOCK_OPPORTUNITY = True

STRONG_DIP_PERCENT = -30
STRONG_PUMP_PERCENT = 30
MIN_ABSOLUTE_MOVE = 0.02
CHEAP_MARKET_MAX_PRICE = 0.01
CHEAP_MARKET_MIN_MOVE = 0.002
MIN_ALERT_LIQUIDITY_POLITICS = 500_000
MIN_ALERT_LIQUIDITY_CRYPTO = 10_000
MIN_ALERT_LIQUIDITY_SPORTS = 10_000
MIN_ALERT_LIQUIDITY_ENTERTAINMENT = 10_000
MIN_ALERT_LIQUIDITY_DEFAULT = 10_000

AUTO_VALUE_ALERTS = False
ALERT_COOLDOWN_HOURS = 24

# AI Engine работает в теневом режиме и не блокирует уведомления.
AI_MIN_TRAINING_SAMPLES = 200
AI_SUCCESS_MOVE_PERCENT = 10.0
AI_SHOW_IN_ALERTS = True

# Opportunity Engine: отдельные уведомления о качественных рынках,
# даже если новое движение цены уже завершилось.
AUTO_OPPORTUNITY_ALERTS = True
OPPORTUNITY_MIN_SCORE = 90
OPPORTUNITY_MIN_AI_QUALITY = 70
OPPORTUNITY_MAX_AI_RISK = 45
OPPORTUNITY_MIN_LIQUIDITY = 100_000
OPPORTUNITY_MAX_PRICE = 0.05
OPPORTUNITY_COOLDOWN_HOURS = 72
OPPORTUNITY_MAX_ALERTS_PER_SCAN = 3

SNAPSHOT_HIGH_SCORE = 70
SNAPSHOT_MEDIUM_SCORE = 40

SNAPSHOT_HIGH_INTERVAL_MINUTES = 5
SNAPSHOT_MEDIUM_INTERVAL_MINUTES = 30
SNAPSHOT_LOW_INTERVAL_MINUTES = 120

SNAPSHOT_FORCE_PRICE_CHANGE_PERCENT = 2.0
SNAPSHOT_FORCE_LIQUIDITY_CHANGE_PERCENT = 5.0
SNAPSHOT_FORCE_VOLUME_CHANGE_PERCENT = 5.0
SNAPSHOT_FORCE_SCORE_CHANGE = 4
SNAPSHOT_FORCE_MARKET_MOVE_PERCENT = 20.0

MARKET_SNAPSHOTS_RETENTION_DAYS = 7
PRICES_RETENTION_DAYS = 30

DATABASE_CLEANUP_INTERVAL_HOURS = 24
DATABASE_VACUUM_INTERVAL_DAYS = 7

# VACUUM запускается, если не менее 15% базы занимает
# пространство от уже удалённых записей.
DATABASE_VACUUM_MIN_FREE_RATIO = 0.15
AI_EXPLAIN_ENABLED = True
AI_EXPLAIN_MAX_FACTORS = 8

# AI Memory Foundation
AI_PARTIAL_MOVE_PERCENT = 3.0
AI_NEUTRAL_MOVE_PERCENT = 3.0
AI_MEMORY_PRIMARY_CHECKPOINT_MINUTES = 1440

# AI Calibration Engine v1.0
CALIBRATION_CHECKPOINT_MINUTES = 1440
CALIBRATION_MIN_HISTORY_SAMPLES = 20
CALIBRATION_GOOD_THRESHOLD = 52.0
CALIBRATION_PREMIUM_THRESHOLD = 72.0

# Similarity Engine v2.1 (observation mode)
SIMILARITY_CHECKPOINT_MINUTES = 1440
SIMILARITY_MAX_CANDIDATES = 1500
SIMILARITY_MAX_NEIGHBORS = 80
SIMILARITY_MIN_SCORE = 60.0
SIMILARITY_MIN_SAMPLES = 8
SIMILARITY_CACHE_SECONDS = 60

# Market Group Engine v2.2
# Related outcomes from one Polymarket event are treated as one signal family.
MARKET_GROUPING_ENABLED = True
MARKET_GROUP_MAX_ALERTS_PER_SCAN = 1
MARKET_GROUP_COOLDOWN_HOURS = 24


# Smart Cooldown Engine v2.3
SMART_COOLDOWN_ENABLED = True
SMART_COOLDOWN_HOURS = 24
SMART_COOLDOWN_PRICE_MOVE_PERCENT = 20.0
SMART_COOLDOWN_QUESTION_MATCH = True
# Feature Importance Engine v1.0 (diagnostic mode)
FEATURE_IMPORTANCE_CHECKPOINT_MINUTES = 1440
FEATURE_IMPORTANCE_MAX_ROWS = 5000
FEATURE_IMPORTANCE_MIN_BUCKET_SAMPLES = 20

# Adaptive AI v0.1 — Shadow Mode (только рекомендации, без применения)
ADAPTIVE_AI_CHECKPOINT_MINUTES = 1440
ADAPTIVE_AI_MAX_ROWS = 5000
ADAPTIVE_AI_MIN_BUCKET_SAMPLES = 20
ADAPTIVE_AI_MIN_SAMPLES = 500
ADAPTIVE_AI_SIMILARITY_MIN_SAMPLES = 100
ADAPTIVE_AI_SHADOW_BLEND = 0.30
ADAPTIVE_AI_MAX_PROPOSAL_DELTA = 0.05

# AI Simulator v1.0 — параллельная проверка текущих и теневых весов
AI_SIMULATOR_CHECKPOINT_MINUTES = 1440
AI_SIMULATOR_MAX_ROWS = 3000
AI_SIMULATOR_TOP_FRACTION = 0.35
AI_SIMULATOR_MIN_EVALUATED = 30


# Signal Confidence Engine v1.0 — Shadow Mode
CONFIDENCE_CHECKPOINT_MINUTES = 1440
CONFIDENCE_MAX_ROWS = 5000
CONFIDENCE_MIN_EVALUATED = 30
CONFIDENCE_SHADOW_MODE = True

# Result Normalization v2.1
# Raw percentages stay in the database and audit. AI diagnostics use a
# signed-log transform with symmetric clipping to reduce tiny-price outliers.
RESULT_RETURN_CAP_PERCENT = 100.0
RESULT_LOG_SCALE_PERCENT = 100.0
RESULT_NORMALIZED_CAP_PERCENT = 100.0

# Price Intelligence Engine v1.0 — Shadow Mode
PRICE_INTELLIGENCE_CHECKPOINT_MINUTES = 1440
PRICE_INTELLIGENCE_MAX_ROWS = 5000
PRICE_INTELLIGENCE_MIN_SAMPLES = 40
PRICE_INTELLIGENCE_SHRINKAGE_SAMPLES = 150
PRICE_INTELLIGENCE_MAX_ADJUSTMENT = 8.0
PRICE_INTELLIGENCE_CACHE_SECONDS = 300
PRICE_INTELLIGENCE_SHADOW_MODE = True

# Feature Intelligence Engine v2.2 — diagnostic / Shadow Mode
FEATURE_INTELLIGENCE_CHECKPOINT_MINUTES = 1440
FEATURE_INTELLIGENCE_MAX_ROWS = 5000
FEATURE_INTELLIGENCE_MIN_BUCKET_SAMPLES = 20
FEATURE_INTELLIGENCE_HISTORY_DAYS = 14
FEATURE_INTELLIGENCE_SHADOW_MODE = True

# Combination Intelligence Engine v1.0 — Shadow Mode
COMBINATION_INTELLIGENCE_CHECKPOINT_MINUTES = 1440
COMBINATION_INTELLIGENCE_MAX_ROWS = 5000
COMBINATION_INTELLIGENCE_MIN_SAMPLES = 30
COMBINATION_INTELLIGENCE_SHRINKAGE_SAMPLES = 100
COMBINATION_INTELLIGENCE_MAX_ORDER = 3
COMBINATION_INTELLIGENCE_TOP_N = 10
COMBINATION_INTELLIGENCE_DIMENSIONS = (
    "score", "ai_quality", "ai_risk", "ml", "liquidity",
    "price_bucket", "liquidity_change", "volume_change",
    "similarity", "category", "direction",
)
COMBINATION_INTELLIGENCE_SHADOW_MODE = True


# Score Calibration Audit v1.0 — Shadow Mode
CALIBRATION_AUDIT_CHECKPOINT_MINUTES = 1440
CALIBRATION_AUDIT_MAX_ROWS = 5000
CALIBRATION_AUDIT_MIN_CONTEXT_SAMPLES = 30
CALIBRATION_AUDIT_SHRINKAGE_SAMPLES = 100
CALIBRATION_AUDIT_SHADOW_MODE = True

# Score Recalibration v1.0 — Shadow Mode
SCORE_RECALIBRATION_CHECKPOINT_MINUTES = 1440
SCORE_RECALIBRATION_MAX_ROWS = 5000
SCORE_RECALIBRATION_SHRINKAGE_SAMPLES = 150
SCORE_RECALIBRATION_MAX_ADJUSTMENT = 12.0
SCORE_RECALIBRATION_SHADOW_MODE = True

# Candidate Strategies v2 — future-only Shadow Mode
AI_SIMULATOR_OPPORTUNITY_PENALTY = 100.0
COMBINATION_CANDIDATE_MIN_SAMPLES = 100
COMBINATION_CANDIDATE_MAX_BONUS = 8.0

# Confidence Recalibration v1.0 — future-only Shadow Mode
CONFIDENCE_RECALIBRATION_SHRINKAGE_SAMPLES = 150
CONFIDENCE_RECALIBRATION_MAX_ADJUSTMENT = 25.0
CONFIDENCE_RECALIBRATION_SHADOW_MODE = True
